env:
  es6: true
  node: true
  jest: true
  browser: true
  commonjs: true
extends:
  - 'prettier'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  line-comment-position:
    - error
    - position: "above"
  no-console: "error"
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
  react/display-name: "off"
  react/jsx-curly-brace-presence: "error"
  yoda:
    - error
    - "always"
  max-lines:
    - error
    - skipBlankLines: true
      skipComments: true
      max: 150
overrides:
  - files:
      - "*.js"
    rules:
      "linebreak-style": "off"
      "@typescript-eslint/no-var-requires": "off"
