env:
  node: true
  es2021: true
  browser: true
  commonjs: true
extends:
  - 'prettier'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-uses-react: "off"
  react/react-in-jsx-scope: "off"
  max-lines:
    - error
    - 80
  linebreak-style:
    - error
    - unix

